VERSION="2.2.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=["GAUTG3WJGV54WJF3ZBNWNSFD73YV7YVBKUN54DW3LQY7RUO57ADIDITX",
"GDQKWSWNTQTEV5AYYISGBLNKOJUBXHFH3TI42UYGKDMNPCINVXR22IBK",
"GBFQ2A5RCBUNEYV2VDSLSGAJRG4CNS3YW2AN4KUH2PTHP3QVJO6C5GSM",
]

[DOCUMENTATION]
ORG_NAME="Stellar Token Marketplace"
ORG_URL="https://xlmtoken.github.io"

# Stellar TOML Home Domain: xlmtoken.github.io

[[CURRENCIES]]
code="ITX"
issuer="GAUTG3WJGV54WJF3ZBNWNSFD73YV7YVBKUN54DW3LQY7RUO57ADIDITX"
display_decimals=7
is_asset_anchored=false
name="Internet Technology Xenogeny"
desc="production of an offspring entirely different from either of the parents. — xenogenetic, xenogenic"
conditions="not limited or restricted in terms of number, quantity, or extent"
image="https://xlmtoken.github.io/itx.jpg"


[[CURRENCIES]]
code="WORLD"
issuer="GDQKWSWNTQTEV5AYYISGBLNKOJUBXHFH3TI42UYGKDMNPCINVXR22IBK"
display_decimals=7
name="WORLD"
desc="The universe is believed to be at least 10 billion light years in diameter and contains a vast number of galaxies; it has been expanding since its creation in the Big Bang about 13 billion years ago. The earth, together with all of its countries, peoples, and natural features. World is a region or group of countries with Human and social interaction."
conditions="WORLD 100% secured assets in the world"
image="https://xlmtoken.github.io/world.png"
is_asset_anchored=true
anchor_asset_type="fiat"
anchor_asset="USD"
status="live"
is_unlimited=true

[[CURRENCIES]]
code="ABILITY"
issuer="GBFQ2A5RCBUNEYV2VDSLSGAJRG4CNS3YW2AN4KUH2PTHP3QVJO6C5GSM"
name="Ability"
desc="Be knowledge of how to do something right"
conditions="932,337,203,685"
image="https://xlmtoken.github.io/ability.png"
display_decimals=7

[[CURRENCIES]]
code="BEAUTY"
issuer="GBFQ2A5RCBUNEYV2VDSLSGAJRG4CNS3YW2AN4KUH2PTHP3QVJO6C5GSM"
name="Beauty"
desc="Beauty, together with art and taste, is the main subject of aesthetics, one of the major branches of philosophy"
conditions="922,337,203,685"
image="https://xlmtoken.github.io/beauty.png"
display_decimals=7

[[CURRENCIES]]
code="CONFIDENCE"
issuer="GBFQ2A5RCBUNEYV2VDSLSGAJRG4CNS3YW2AN4KUH2PTHP3QVJO6C5GSM"
name="Confidence"
desc="Belief in success, regardless of failure"
conditions="922,337,203,685"
image="https://xlmtoken.github.io/confidence.png"
display_decimals=7

[[CURRENCIES]]
code="DREAM"
issuer="GBFQ2A5RCBUNEYV2VDSLSGAJRG4CNS3YW2AN4KUH2PTHP3QVJO6C5GSM"
name="Dream"
desc="Dreaming and sleep are intertwined"
conditions="922,337,203,685"
image="https://xlmtoken.github.io/dream.png"
display_decimals=7

[[CURRENCIES]]
code="EXCELLENCE"
issuer="GBFQ2A5RCBUNEYV2VDSLSGAJRG4CNS3YW2AN4KUH2PTHP3QVJO6C5GSM"
name="Excellence"
desc="Something in which one excels"
conditions="922,337,203,685"
image="https://xlmtoken.github.io/excellence.png"
display_decimals=7

[[CURRENCIES]]
code="FINENESS"
issuer="GBFQ2A5RCBUNEYV2VDSLSGAJRG4CNS3YW2AN4KUH2PTHP3QVJO6C5GSM"
name="Fineness"
desc="The quality of being fine"
conditions="922,337,203,685"
image="https://xlmtoken.github.io/fineness.png"
display_decimals=7

[[CURRENCIES]]
code="GLAMOUR"
issuer="GBFQ2A5RCBUNEYV2VDSLSGAJRG4CNS3YW2AN4KUH2PTHP3QVJO6C5GSM"
name="Glamour"
desc="A combination of charm and good looks"
conditions="922,337,203,685"
image="https://xlmtoken.github.io/glamour.png"
display_decimals=7

[[CURRENCIES]]
code="HEALTH"
issuer="GBFQ2A5RCBUNEYV2VDSLSGAJRG4CNS3YW2AN4KUH2PTHP3QVJO6C5GSM"
name="Health"
desc="Condition in which is thriving"
conditions="922,337,203,685"
image="https://xlmtoken.github.io/health.png"
display_decimals=7

[[CURRENCIES]]
code="INTELLIGENCE"
issuer="GBFQ2A5RCBUNEYV2VDSLSGAJRG4CNS3YW2AN4KUH2PTHP3QVJO6C5GSM"
name="Intelligence"
desc="Intelligence is what you do when you don't know what to do"
conditions="922,337,203,685"
image="https://xlmtoken.github.io/intelligence.png"
display_decimals=7

[[CURRENCIES]]
code="JUSTICE"
issuer="GBFQ2A5RCBUNEYV2VDSLSGAJRG4CNS3YW2AN4KUH2PTHP3QVJO6C5GSM"
name="Justice"
desc="Human rights and The rule of law"
conditions="922,337,203,685"
image="https://xlmtoken.github.io/justice.png"
display_decimals=7

[[CURRENCIES]]
code="LUXURY"
issuer="GBFQ2A5RCBUNEYV2VDSLSGAJRG4CNS3YW2AN4KUH2PTHP3QVJO6C5GSM"
name="Luxury"
desc="I define luxury as the details that exceed your expectations and please the five senses"
conditions="922,337,203,685"
image="https://xlmtoken.github.io/luxury.png"
display_decimals=7

[[CURRENCIES]]
code="MERCY"
issuer="GBFQ2A5RCBUNEYV2VDSLSGAJRG4CNS3YW2AN4KUH2PTHP3QVJO6C5GSM"
name="Mercy"
desc="God’s mercy means His pity, compassion, and kindness toward people"
conditions="922,337,203,685"
image="https://xlmtoken.github.io/mercy.png"
display_decimals=7

[[PRINCIPALS]]
name="XLM Token Support Team"
email="lumenxstellar@yahoo.com"

# Token was issued using the open and inclusive Stellar blockchain network.
